{{- if not .Values.config.existingConfigMap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aura.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aura.labels" . | nindent 4 }}
data:
  {{- if eq (kindOf .Values.config.content) "map" }}
  {{- range $name, $toml := .Values.config.content }}
  {{ $name }}: |
    {{- $toml | nindent 4 }}
  {{- end }}
  {{- else if .Values.config.content }}
  config.toml: |
    {{- .Values.config.content | nindent 4 }}
  {{- else }}
  config.toml: |
    {{- include "aura.toml.renderConfig" . | nindent 4 }}
  {{- end }}
{{- end }}
