{{- if include "aura.createSecret" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aura.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aura.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.anthropicApiKey }}
  ANTHROPIC_API_KEY: {{ .Values.secrets.anthropicApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.mezmoApiKey }}
  MEZMO_API_KEY: {{ .Values.secrets.mezmoApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.awsAccessKeyId }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.awsAccessKeyId | quote }}
  {{- end }}
  {{- if .Values.secrets.awsSecretAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.awsSecretAccessKey | quote }}
  {{- end }}
{{- end }}
