#!/usr/bin/env bash
# Open a pull request on the AURA Homebrew tap bumping every formula to a
# released version. Reads the per-platform binary sha256 values from the
# release checksums file (the same file `make verify-binaries` writes), so it
# needs no network access to compute hashes.
#
# Environment:
#   CHECKSUMS_FILE     - path to the sha256 checksums file (default: dist/checksums.txt)
#   GH_TOKEN / GITHUB_TOKEN - token with contents + pull-requests write on the tap
set -euo pipefail

VERSION="${1#v}"
[ -n "${VERSION}" ] || { echo "usage: $0 <version>" >&2; exit 1; }

TAP_REPO="mezmo/homebrew-tap"
CHECKSUMS="${CHECKSUMS_FILE:-dist/checksums.txt}"
TOKEN="${GH_TOKEN:-${GITHUB_TOKEN:-}}"
BRANCH="bump-aura-v${VERSION}"

[ -f "${CHECKSUMS}" ] || { echo "error: checksums file not found: ${CHECKSUMS}" >&2; exit 1; }
[ -n "${TOKEN}" ] || { echo "error: GH_TOKEN or GITHUB_TOKEN required" >&2; exit 1; }
command -v gh >/dev/null 2>&1 || { echo "error: gh CLI not found" >&2; exit 1; }

CHECKSUMS="$(cd "$(dirname "${CHECKSUMS}")" && pwd)/$(basename "${CHECKSUMS}")"

WORKDIR="$(mktemp -d)"
trap 'rm -rf "${WORKDIR}"' EXIT

export GH_TOKEN="${TOKEN}"
git clone --depth 1 "https://x-access-token:${TOKEN}@github.com/${TAP_REPO}.git" "${WORKDIR}/tap"
cd "${WORKDIR}/tap"
git checkout -b "${BRANCH}"

# In each formula, bump the version line and set every `sha256` to the checksum
# of the asset named in the `url` line directly above it.
for f in Formula/*.rb; do
  awk -v ver="${VERSION}" -v ck="${CHECKSUMS}" '
    BEGIN { while ((getline l < ck) > 0) { n = split(l, a, /  +/); sums[a[2]] = a[1] } }
    /^[[:space:]]*version "/ { sub(/"[^"]+"/, "\"" ver "\""); print; next }
    /^[[:space:]]*url "/ {
      m = split($0, p, "/"); asset = p[m]; sub(/".*/, "", asset); pend = asset; print; next
    }
    pend != "" && /sha256 "/ {
      if (!(pend in sums)) { print "error: no checksum for " pend > "/dev/stderr"; exit 2 }
      sub(/"[0-9a-f]+"/, "\"" sums[pend] "\""); pend = ""; print; next
    }
    { print }
  ' "${f}" > "${f}.tmp"
  mv "${f}.tmp" "${f}"
done

if git diff --quiet; then
  echo "Formulae already at v${VERSION}; nothing to do"
  exit 0
fi

git commit -am "chore: bump aura formulae to v${VERSION}"
git push --force-with-lease -u origin "${BRANCH}"

if gh pr view "${BRANCH}" --repo "${TAP_REPO}" >/dev/null 2>&1; then
  echo "PR for ${BRANCH} already open; branch updated"
else
  gh pr create --repo "${TAP_REPO}" --head "${BRANCH}" --base main \
    --title "chore: bump aura formulae to v${VERSION}" \
    --body "Automated formula bump for aura \`v${VERSION}\`, generated by the aura release pipeline."
fi
